---

- hosts: web-servers
  become: yes
  tasks:

  - name: remove apache2 package ubuntu
    tags: ubuntu,apache,web
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove apache package CentOS
    tags: centos,apache,web
    package:
      name:
        - nttpd
        - php
      state: absent
    when: ansible_distribution == "CentOS"

- hosts: db-servers
  become: yes
  tasks:

  - name: remove mariadb Ubuntu
    tags: ubuntu,db,mariadb
    apt:
      name: mariadb-server
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove mariadb CentOS
    tags: ubuntu,db,mariadb
    package:
      name: mariadb-server
      state: absent
    when: ansible_distribution == "CentOS"
