---

- hosts: all
  become: yes
  tasks:
  
  - name: update packages Ubuntu
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: update packages CentOS
    tags: always
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web-servers
  become: yes
  tasks:

  - name: install apache2 package Ubuntu
    tags: ubuntu,apache,web
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package CentOS
    tags: centos,httpd,web
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: copy html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db-servers
  become: yes
  tasks:

  - name: install mariadb CentOS
    tags: centos,mariadb,db
    package:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb Ubuntua
    tags: ubuntu,mariadb,db
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: fileservers
  become: yes
  tasks:

  - name: install samba
    tags: samba    
    package:
      name: samba
      state: latest

